---
title: "Exploratory Data Analysis Quiz 1"
subtitle: "Johns Hopkins University Coursera"
author: "Nathaniel Lai"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For lecture material, see: 

https://github.com/DataScienceSpecialization/courses/blob/master/04_ExploratoryAnalysis/PlottingBase/index.Rmd.

https://github.com/DataScienceSpecialization/courses/tree/master/04_ExploratoryAnalysis/GraphicsDevices

\vspace{1 cm}

Question 1
Which of the following is a principle of analytic graphics?

* Show comparisons

\vspace{0.3 cm}
Question 2
What is the role of exploratory graphs in data analysis?

* The goal is for personal understanding.

\vspace{0.3 cm}
Question 3
Which of the following is true about the base plotting system?

* Plots are created and annotated with separate functions

\vspace{0.3 cm}
Question 4
Which of the following is an example of a valid graphics device in R?

* A PDF file

\vspace{0.3 cm}
Question 3
Which of the following is an example of a vector graphics device in R?

* Postscript

\vspace{0.3 cm}
Question 6
Bitmapped file formats can be most useful for

* Scatterplots with many many points

\vspace{0.3 cm}
Question 7
Which of the following functions is typically used to add elements to a plot in the base graphics system?

* `text()`

\vspace{0.3 cm}
Question 8
Which function opens the screen graphics device for the Mac and Window?

* `quartz()`, `window()` 

\vspace{0.3 cm}
Question 9
What does the 'pch' option to par() control?

* the plotting symbol/character in the base graphics system

\vspace{0.3 cm}
Question 10
If I want to save a plot to a PDF file, which of the following is a correct way of doing that?

* Construct the plot on the screen device and then copy it to a PDF file with `dev.copy2pdf()`